aof: "yes"
daemonize: "yes"
pass: "requirepass my_redis_pass"
bind: "127.0.0.1"
port: 6379
dest_dir: /tmp/redis/
redis: &redis
  push:
    - src: redis/bin/redis-server
      dest: ./
    - src: start.sh
      dest: ./
    - src: redis_template.conf
      dest: ./redis.conf
      template: yes
  start: "./start.sh start redis-server redis.conf"
  stop: "./start.sh stop redis-server"
  state: "./start.sh state redis-server"
